/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary":                   "var(--color-primary)",
        "primary-container":         "var(--color-primary-container)",
        "primary-fixed":             "var(--color-primary-fixed)",
        "primary-fixed-dim":         "var(--color-primary-fixed-dim)",
        "on-primary":                "var(--color-on-primary)",
        "on-primary-fixed":          "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant":  "var(--color-on-primary-fixed-variant)",
        "inverse-primary":           "var(--color-inverse-primary)",
        "secondary":                 "var(--color-secondary)",
        "secondary-container":       "var(--color-secondary-container)",
        "secondary-fixed":           "var(--color-secondary-fixed)",
        "secondary-fixed-dim":       "var(--color-secondary-fixed-dim)",
        "on-secondary":              "var(--color-on-secondary)",
        "on-secondary-container":    "var(--color-on-secondary-container)",
        "on-secondary-fixed":        "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant":"var(--color-on-secondary-fixed-variant)",
        "tertiary":                  "var(--color-tertiary)",
        "tertiary-container":        "var(--color-tertiary-container)",
        "tertiary-fixed":            "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim":        "var(--color-tertiary-fixed-dim)",
        "on-tertiary":               "var(--color-on-tertiary)",
        "on-tertiary-container":     "var(--color-on-tertiary-container)",
        "on-tertiary-fixed":         "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "background":                "var(--color-background)",
        "surface":                   "var(--color-surface)",
        "surface-bright":            "var(--color-surface-bright)",
        "surface-dim":               "var(--color-surface-dim)",
        "surface-container":         "var(--color-surface-container)",
        "surface-container-low":     "var(--color-surface-container-low)",
        "surface-container-high":    "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-lowest":  "var(--color-surface-container-lowest)",
        "surface-variant":           "var(--color-surface-variant)",
        "surface-tint":              "var(--color-surface-tint)",
        "on-background":             "var(--color-on-background)",
        "on-surface":                "var(--color-on-surface)",
        "on-surface-variant":        "var(--color-on-surface-variant)",
        "error":                     "var(--color-error)",
        "error-container":           "var(--color-error-container)",
        "on-error":                  "var(--color-on-error)",
        "on-error-container":        "var(--color-on-error-container)",
        "outline":                   "var(--color-outline)",
        "outline-variant":           "var(--color-outline-variant)",
        "project-center":            "var(--color-project-center)",
        "status-pending-bg":   "var(--color-status-pending-bg)",
        "status-pending-text": "var(--color-status-pending-text)",
        "status-success-bg":   "var(--color-status-success-bg)",
        "status-success-text": "var(--color-status-success-text)",
        "status-error-bg":     "var(--color-status-error-bg)",
        "status-error-text":   "var(--color-status-error-text)",
        "status-info-bg":      "var(--color-status-info-bg)",
        "status-info-text":    "var(--color-status-info-text)",
        "status-warning-bg":   "var(--color-status-warning-bg)",
        "status-warning-text": "var(--color-status-warning-text)",
        "status-purple-bg":    "var(--color-status-purple-bg)",
        "status-purple-text":  "var(--color-status-purple-text)",

        /* Category icon surface tints */
        "orange-surface": "#FFF0E6",
        "blue-surface":   "#EFF6FF",
        "yellow-surface": "#FEFCE8",
        "red-surface":    "#FFF1F2",
      },

      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Manrope", "sans-serif"],
        label:    ["Manrope", "sans-serif"],
        manrope:  ["Manrope", "sans-serif"],
      },

      borderRadius: {
        DEFAULT: "0.375rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },

      screens: {
        sm:  "640px",
        md:  "768px",
        lg:  "1024px",
        xl:  "1280px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
